openapi: "3.0.0"
info:
  version: "0.0.1"
  title: "API Резюме"
  description: "Сайт Job - модуль резюме"
servers:
  - url: "http://localhost:9000"
paths:
  /cvs:
    get:
      summary: "Получить список резюме"
      responses:
        200:
          description: "OK"
  /cv?id={id}:
    get:
      summary: "Получить резюме"
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        200:
          description: "OK"
