openapi: "3.0.0"
info:
  version: "0.0.1"
  title: "API"
  description: "Сайт Job"
servers:
  - url: "http://localhost:8000"
paths:
    /api/cvs:
        get:
          summary: "Получить список резюме"
          tags:
            - Резюме
          responses:
            200:
              description: "OK"
        post:
          summary: "Добавить резюме"
          tags:
            - Резюме
          requestBody:
            content:
              application/x-www-form-urlencoded:
                schema:
                  type: object
                  properties:
                    user_id:
                      type: integer
                      required: true
                    section_id:
                      type: integer
                      required: true
                    title:
                      type: string
                      required: true
                    content:
                      type: string
                      required: true
                    datetime:
                      type: string
                      format: date-time
                      description: 'Например "2018-06-11 11:24:04"'
                      required: true
                    
          responses:
            200:
              description: "OK"
    /api/cvs/{id}:
        get:
          summary: "Получить резюме"
          tags:
            - Резюме
          parameters:
            - in: path
              name: id
              schema:
                type: integer
              required: true
          responses:
            200:
              description: "OK"
        post:
          summary: "Изменить резюме"
          tags:
            - Резюме
          requestBody:
            content:
              multipart/form-data:
                schema:
                  type: object
                  properties:
                    user_id:
                      type: integer
                      required: true
                    section_id:
                      type: integer
                      required: true
                    title:
                      type: string
                      required: true
                    content:
                      type: string
                      required: true
                    datetime:
                      type: string
                      format: date-time
                      description: 'Например "2018-06-11 11:24:04"'
                      required: true
          parameters:
            - in: path
              name: id
              schema:
                type: integer
              required: true
          responses:
            200:
              description: "OK"
        delete:
          summary: "Удалить резюме"
          tags:
            - Резюме
          parameters:
            - in: path
              name: id
              schema:
                type: integer
              required: true
          responses:
            200:
              description: "OK"
    /api/vacancy:
        get:
          summary: "Получить список вакансий"
          tags:
            - Вакансия
          responses:
            200:
              description: "OK"
        post:
          summary: "Добавить вакансию"
          tags:
            - Вакансия
          requestBody:
            content:
              application/x-www-form-urlencoded:
                schema:
                  type: object
                  properties:
                    user_id:
                      type: integer
                      required: true
                    section_id:
                      type: integer
                      required: true
                    title:
                      type: string
                      required: true
                    content:
                      type: string
                      required: true
                    salary:
                      type: integer
                      required: true
                    experience:
                      type: integer
                      required: true
                    is_main:
                      type: integer
                      required: true
                    is_partnership:
                      type: integer
                      required: true
                    is_remote:
                      type: integer
                      required: true
                    datetime:
                      type: string
                      format: date-time
                      description: 'Например "2018-06-11 11:24:04"'
                      required: true
                    
          responses:
            200:
              description: "OK"
    /api/vacancy/{id}:
        get:
          summary: "Получить вакансию"
          tags:
            - Вакансия
          parameters:
            - in: path
              name: id
              schema:
                type: integer
              required: true
          responses:
            200:
              description: "OK"
        post:
          summary: "Изменить вакансию"
          tags:
            - Вакансия
          requestBody:
            content:
              multipart/form-data:
                schema:
                  type: object
                  properties:
                    user_id:
                      type: integer
                      required: true
                    section_id:
                      type: integer
                      required: true
                    title:
                      type: string
                      required: true
                    content:
                      type: string
                      required: true
                    salary:
                      type: integer
                      required: true
                    experience:
                      type: integer
                      required: true
                    is_main:
                      type: integer
                      required: true
                    is_partnership:
                      type: integer
                      required: true
                    is_remote:
                      type: integer
                      required: true
                    datetime:
                      type: string
                      format: date-time
                      description: 'Например "2018-06-11 11:24:04"'
                      required: true
          parameters:
            - in: path
              name: id
              schema:
                type: integer
              required: true
          responses:
            200:
              description: "OK"
        delete:
          summary: "Удалить вакансию"
          tags:
            - Вакансия
          parameters:
            - in: path
              name: id
              schema:
                type: integer
              required: true
          responses:
            200:
              description: "OK"