name: Deploy

on:
  push:
  workflow_dispatch:

env:
  DEPLOY_PATH: /var/www/class-test.ru/app
  SOURCE_PATH: .

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get branch name
        shell: bash
        run: |
          echo "BRANCH_NAME=$(echo ${GITHUB_REF##*/} | sed 's/\//-/g' | sed 's/\./_/g'| sed 's/^feature-//g')" >> $GITHUB_ENV

      - name: Print branch name
        run: |
          echo "Branch name: ${BRANCH_NAME}"

      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          port: ${{ secrets.DEPLOY_SERVER_PORT }}
          username: ${{ secrets.DEPLOY_SERVER_USERNAME }}
          key: ${{ secrets.DEPLOY_SERVER_KEY }}
          source: ${{ env.SOURCE_PATH }}
          target: ${{ env.DEPLOY_PATH }}/${{ env.BRANCH_NAME }}
          strip_components: 1
          overwrite: true
          debug: true

      - name: Print Info
        run: echo "Deployed at https://${BRANCH_NAME}.app.class-test.ru/"

      - name: Create .env config
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          port: ${{ secrets.DEPLOY_SERVER_PORT }}
          username: ${{ secrets.DEPLOY_SERVER_USERNAME }}
          key: ${{ secrets.DEPLOY_SERVER_KEY }}
          script: |
            cat <<EOF > ${{ env.DEPLOY_PATH }}/${{ env.BRANCH_NAME }}/.env
            DSN="mysql:host=mariadb;port=3306;dbname=job;charset=utf8;"
            DB_USER="job"
            DB_PASSWORD="job"
            DEBUG="false"
            EOF
            docker exec -i job-site_php /usr/local/bin/composer install --working-dir=/var/www/html/${{env.BRANCH_NAME}}
