name: Deploy

on: [push]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  DEPLOY_PATH: /var/www/class-test.ru/app
  BUILD_SCRIPT_OUTPUT: .

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get branch name
        shell: bash
        run: |
          echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g' | sed 's/\./_/g'| sed 's/^feature-//g')"

      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          port: ${{ secrets.DEPLOY_SERVER_PORT }}
          username: ${{ secrets.DEPLOY_SERVER_USERNAME }}
          key: ${{ secrets.DEPLOY_SERVER_KEY }}
          source: ${{ env.BUILD_SCRIPT_OUTPUT }}
          target: ${{ env.DEPLOY_PATH }}/${{ env.BRANCH_NAME }}
          strip_components: 1

      - name: Print Info
        run: echo "Deployed at https://${BRANCH_NAME}.app.class-test.ru/"
